"use client"

import { submitProductReview, type ProductReviewsResponse, type ReviewFormState } from "@lib/data/product-reviews"
import Link from "next/link"
import { usePathname, useSearchParams } from "next/navigation"
import { FormEvent, useActionState, useMemo, useState } from "react"

type Props = { productId: string; data: ProductReviewsResponse; canReview: boolean }
const initialState: ReviewFormState = {}

export default function ProductReviews({ productId, data, canReview }: Props) {
  const pathname = usePathname()
  const searchParams = useSearchParams()
  const [state, action, pending] = useActionState(submitProductReview, initialState)
  const [expanded, setExpanded] = useState<Record<string, boolean>>({})
  const href = (updates: Record<string, string | null>) => {
    const params = new URLSearchParams(searchParams.toString())
    Object.entries(updates).forEach(([key, value]) => value === null ? params.delete(key) : params.set(key, value))
    return `${pathname}?${params.toString()}#reviews`
  }
  const pages = useMemo(() => pageItems(data.page, data.page_count), [data.page, data.page_count])
  const maxDistribution = Math.max(1, ...Object.values(data.rating_distribution))

  return <section id="reviews" className="border-t border-grey-20 bg-paper py-14 small:py-20" aria-labelledby="reviews-title">
    <div className="pbn-container">
      <div className="mb-10 flex flex-col gap-3 small:flex-row small:items-end small:justify-between">
        <div><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-brand">From the PetBoxNest community</p><h2 id="reviews-title" className="text-3xl font-bold tracking-tight text-ink small:text-5xl">Product reviews</h2><p className="mt-2 max-w-2xl text-base text-grey-60">Real feedback is reviewed before publishing, so shoppers can make confident choices for their pets.</p></div>
        {data.count > 0 && <a href="#review-list" className="pbn-focus min-h-11 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">Read {data.count} {data.count === 1 ? "review" : "reviews"}</a>}
      </div>

      <div className="grid gap-6 large:grid-cols-[340px_minmax(0,1fr)]">
        <aside className="rounded-[28px] border border-grey-20 bg-cream p-6 small:p-8">
          {data.count ? <><div className="flex items-end gap-3"><strong className="text-6xl leading-none text-ink">{data.average_rating.toFixed(1)}</strong><div><Stars rating={Math.round(data.average_rating)} /><p className="mt-1 text-sm text-grey-60">Based on {data.count} approved reviews</p></div></div><div className="mt-7 space-y-3">{[5,4,3,2,1].map((star) => { const count = data.rating_distribution[star as 1|2|3|4|5] || 0; return <Link key={star} href={href({ review_rating: String(star), review_page: "1" })} className="pbn-focus grid min-h-10 grid-cols-[48px_1fr_30px] items-center gap-2 rounded-lg text-sm hover:text-brand"><span>{star} ★</span><span className="h-2 overflow-hidden rounded-full bg-grey-20"><span className="block h-full rounded-full bg-brand" style={{ width: `${(count/maxDistribution)*100}%` }}/></span><span className="text-right text-grey-60">{count}</span></Link> })}</div></> : <div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-yellow text-2xl">★</div><h3 className="mt-5 text-2xl font-bold text-ink">Be the first to review</h3><p className="mt-2 text-sm leading-6 text-grey-60">Share what worked for you and help another pet parent choose well.</p></div>}

          <div className="mt-8 border-t border-grey-20 pt-7">
            {canReview ? <details open={data.count === 0} className="group"><summary className="pbn-focus cursor-pointer list-none rounded-full bg-brand px-5 py-3 text-center text-sm font-bold text-white">Write a review</summary><form action={action} className="mt-5 space-y-4"><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="path" value={pathname}/><fieldset><legend className="mb-2 text-sm font-bold text-ink">Your rating</legend><div className="flex flex-row-reverse justify-end gap-1">{[5,4,3,2,1].map((star) => <label key={star} className="group/star cursor-pointer"><input className="peer sr-only" required type="radio" name="rating" value={star}/><span className="block min-h-11 min-w-9 text-center text-3xl text-grey-30 peer-checked:text-yellow group-hover/star:text-yellow">★</span></label>)}</div></fieldset><label className="block text-sm font-bold text-ink">Title <span className="font-normal text-grey-60">(optional)</span><input name="title" maxLength={120} className="pbn-focus mt-2 min-h-11 w-full rounded-xl border border-grey-30 bg-white px-3"/></label><label className="block text-sm font-bold text-ink">Your review<textarea name="content" required minLength={10} maxLength={2000} rows={5} className="pbn-focus mt-2 w-full rounded-xl border border-grey-30 bg-white p-3"/></label><button disabled={pending} className="pbn-focus min-h-11 w-full rounded-full bg-ink px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{pending ? "Submitting…" : "Submit for review"}</button>{state.success && <p role="status" className="rounded-xl bg-mint p-3 text-sm font-semibold text-ink">Thank you. Your review will appear after approval.</p>}{state.error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}</form></details> : <div><p className="text-sm text-grey-60">Sign in to share your experience with this product.</p><Link href={`/account?redirect=${encodeURIComponent(pathname + "#reviews")}`} className="pbn-focus mt-3 inline-flex min-h-11 items-center rounded-full border-2 border-ink px-5 py-2 text-sm font-bold text-ink">Sign in to review</Link></div>}
          </div>
        </aside>

        <div id="review-list">
          <form action={pathname} className="mb-5 grid gap-3 rounded-2xl border border-grey-20 bg-white p-3 xsmall:grid-cols-[1fr_auto_auto]">
            <input name="review_q" defaultValue={searchParams.get("review_q") || ""} placeholder="Search reviews" aria-label="Search reviews" className="pbn-focus min-h-11 rounded-xl border border-grey-20 px-4"/>
            <select name="review_sort" defaultValue={searchParams.get("review_sort") || "newest"} aria-label="Sort reviews" className="pbn-focus min-h-11 rounded-xl border border-grey-20 bg-white px-3"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest rating</option><option value="lowest">Lowest rating</option></select>
            <button className="pbn-focus min-h-11 rounded-xl bg-ink px-5 font-bold text-white">Apply</button>
          </form>
          {(searchParams.get("review_rating") || searchParams.get("review_q")) && <Link href={href({ review_rating: null, review_q: null, review_page: "1" })} className="pbn-focus mb-4 inline-flex min-h-11 items-center text-sm font-bold text-brand">Clear review filters</Link>}
          {data.reviews.length ? <div className="space-y-4">{data.reviews.map((review) => { const long = review.content.length > 360; const shown = expanded[review.id] || !long ? review.content : `${review.content.slice(0, 360)}…`; return <article key={review.id} className="rounded-[24px] border border-grey-20 bg-white p-5 small:p-7"><div className="flex flex-col gap-2 xsmall:flex-row xsmall:items-center xsmall:justify-between"><Stars rating={review.rating}/><time className="text-xs font-semibold uppercase tracking-wide text-grey-50" dateTime={review.created_at}>{new Intl.DateTimeFormat("en-US", { year: "numeric", month: "short", day: "numeric" }).format(new Date(review.created_at))}</time></div>{review.title && <h3 className="mt-4 text-xl font-bold text-ink">{review.title}</h3>}<p className="mt-3 whitespace-pre-wrap text-[15px] leading-7 text-grey-70">{shown}</p>{long && <button onClick={() => setExpanded((current) => ({ ...current, [review.id]: !current[review.id] }))} className="pbn-focus mt-2 min-h-11 text-sm font-bold text-brand">{expanded[review.id] ? "Show less" : "Read more"}</button>}<p className="mt-4 text-sm font-bold text-ink">{review.reviewer_name}</p>{review.reply && <div className="mt-5 rounded-2xl border-l-4 border-brand bg-lavender/40 p-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand">PetBoxNest reply</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-grey-70">{review.reply.content}</p></div>}</article> })}</div> : <div className="rounded-[24px] border border-dashed border-grey-30 bg-white px-6 py-16 text-center"><h3 className="text-xl font-bold text-ink">No reviews found</h3><p className="mt-2 text-grey-60">Try clearing the filters or be the first to share feedback.</p></div>}
          {data.page_count > 1 && <nav className="mt-7 flex flex-wrap items-center justify-center gap-2" aria-label="Review pages"><p className="w-full text-center text-sm font-semibold text-grey-60">Page {data.page} of {data.page_count}</p><Link aria-disabled={data.page <= 1} href={href({ review_page: String(Math.max(1, data.page - 1)) })} className="pbn-focus grid min-h-11 min-w-11 place-items-center rounded-full border border-grey-30 px-3 font-bold aria-disabled:pointer-events-none aria-disabled:opacity-40">Prev</Link>{pages.map((page, index) => page === null ? <span key={`ellipsis-${index}`} className="px-2">…</span> : <Link key={page} aria-current={page === data.page ? "page" : undefined} href={href({ review_page: String(page) })} className="pbn-focus grid min-h-11 min-w-11 place-items-center rounded-full border border-grey-30 font-bold aria-[current=page]:border-brand aria-[current=page]:bg-brand aria-[current=page]:text-white">{page}</Link>)}<Link aria-disabled={data.page >= data.page_count} href={href({ review_page: String(Math.min(data.page_count, data.page + 1)) })} className="pbn-focus grid min-h-11 min-w-11 place-items-center rounded-full border border-grey-30 px-3 font-bold aria-disabled:pointer-events-none aria-disabled:opacity-40">Next</Link><Jump current={data.page} total={data.page_count} href={href}/></nav>}
        </div>
      </div>
    </div>
  </section>
}

function Stars({ rating }: { rating: number }) { return <span className="text-xl tracking-wider text-yellow" role="img" aria-label={`${rating} out of 5 stars`}>{"★".repeat(rating)}<span className="text-grey-20">{"★".repeat(5-rating)}</span></span> }
function pageItems(current: number, total: number): Array<number|null> { if (total <= 7) return Array.from({ length: total }, (_, i) => i + 1); const set = new Set([1,total,current-1,current,current+1].filter((page) => page >= 1 && page <= total)); const sorted = Array.from(set).sort((a,b) => a-b); const output: Array<number|null> = []; sorted.forEach((page, index) => { if (index && page - sorted[index-1] > 1) output.push(null); output.push(page) }); return output }
function Jump({ current, total, href }: { current: number; total: number; href: (updates: Record<string,string|null>) => string }) { const [page, setPage] = useState(String(current)); const submit = (event: FormEvent) => { event.preventDefault(); const next = Math.min(total, Math.max(1, Number(page) || 1)); window.location.href = href({ review_page: String(next) }) }; return <form onSubmit={submit} className="ml-2 flex items-center gap-2"><label className="text-sm font-semibold text-grey-60">Go to <input value={page} onChange={(e) => setPage(e.target.value)} type="number" min={1} max={total} className="pbn-focus ml-1 h-11 w-16 rounded-xl border border-grey-30 px-2"/></label><button className="pbn-focus min-h-11 rounded-full bg-ink px-4 text-sm font-bold text-white">Go</button></form> }
