packages:
  - "apps/**"
  - "!apps/backend/.medusa/**"

overrides:
  "@types/react": "19.0.5"
  "@types/react-dom": "19.0.5"

allowBuilds:
  "@medusajs/telemetry": true
  "@swc/core": true
  es5-ext: false
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

patchedDependencies:
  '@medusajs/loyalty-plugin@2.19.0': patches/@medusajs__loyalty-plugin@2.19.0.patch
